name: Update README Date & Time (IST)

on:
  schedule:
    - cron: '30 2 * * *'    # 8:00 AM IST
    - cron: '30 14 * * *'   # 8:00 PM IST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Update README with Indian Date & Time
        run: |
          DAY=$(TZ='Asia/Kolkata' date '+%A')
          DATE=$(TZ='Asia/Kolkata' date '+%d %B %Y')
          TIME=$(TZ='Asia/Kolkata' date '+%I:%M:%S %p IST')

          TEXT="📅 $DAY, $DATE | 🕒 $TIME"

          awk '
          /<!--START_SECTION:date-->/ {print; print "'"$TEXT"'"; skip=1; next}
          /<!--END_SECTION:date-->/ {skip=0}
          !skip
          ' README.md > temp.md && mv temp.md README.md

      - name: Commit Changes
        run: |
          git config --global user.name "mukund-ahire"
          git config --global user.email "mukundahire.work@gmail.com"

          git add README.md
          git commit -m "Updated README with IST time" || echo "No changes to commit"
          git push
