name: Update README Date

on:
  schedule:
    # 🌅 Morning - 9:00 AM IST (03:30 UTC)
    - cron: "30 3 * * *"

    # 🌇 Evening - 5:00 PM IST (11:30 UTC)
    - cron: "30 11 * * *"

    # 🌙 Night - 9:30 PM IST (16:00 UTC)
    - cron: "0 16 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Update README
        run: node scripts/update-date.js

      - name: Commit Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions.noreply.github.com"

          git add README.md

          git diff --staged --quiet || (
            git commit -m "docs: update README"
            git push
          )
